# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - left_gripper_controller

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - left_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - left_elbow_joint
      - left_wrist_roll_joint
      - left_wrist_pitch_joint
      - left_wrist_yaw_joint
    action_ns: follow_joint_trajectory
    default: true

  left_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - left_hand_thumb_0_joint
      - left_hand_thumb_1_joint
      - left_hand_thumb_2_joint
      - left_hand_index_0_joint
      - left_hand_index_1_joint
      - left_hand_middle_0_joint
      - left_hand_middle_1_joint
    action_ns: follow_joint_trajectory
    default: true