# Default initial positions for g1_dual_arm's ros2_control fake system

initial_positions:
  right_elbow_joint: 0
  right_shoulder_pitch_joint: 0
  right_shoulder_roll_joint: 0
  right_shoulder_yaw_joint: 0
  right_wrist_pitch_joint: 0
  right_wrist_roll_joint: 0
  right_wrist_yaw_joint: 0